name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - "Makefile"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"
  schedule:
    # Every Monday at 6 AM (EDT)
    - cron: "0 6 * * 1"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build multi-arch and push yarn v1.22
        run: make ciDeploy
        env:
          INSTALL_YARN_BERRY: false
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build multi-arch and push yarn berry
        run: make ciDeploy
        env:
          INSTALL_YARN_BERRY: true
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
