name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Inspect builder
      run: |
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: Test
      run: make ciTest

